[package]
name = "cs_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
gtk4 = "0.7"
glib = "0.18"
nalgebra = "0.32"
rand = "0.8"
